# Site settings
title: 2je
description: "2je portfolio test"
url: "http://2je.github.io"
author:
  name: "The Review Index"
  email: "dyutibarma@gmail.com"
  url: "https://thereviewindex.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false

#collections
collections:
  edition:
    title: edition
    output: true
  vol:
    title: vol
    output: true
   
